### ISSUE TITLE
New investment time

### ISSUE THREAD

**Issue by matteogalliani** [nebulab/playbook#328]
We should feature our brand new Investment Time policy, and at the same time delete the Investment Friday one by removing or editing the following content:

- [ ] https://playbook.nebulab.it/personal-growth/investment-fridays/
- [ ] https://playbook.nebulab.it/people-ops/benefits/
- [ ] https://playbook.nebulab.it/mentoring-people/promoting-growth/#tackling-the-right-project

Related to #324 

## Todo

- [x] I have added this issue to the [Workflow](https://github.com/nebulab/playbook/projects/1) GitHub project.
- [x] I have added the appropriate labels to this issue.
